Task 0-modified for 0x0C-web_server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -14,3 +14,9 @@ path_to_file=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
+
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "File transfer failed."
+fi
